### ISSUE TITLE
Indexing Fatal Exception

### ISSUE THREAD

**Issue by IvanLieckens** [HedgehogDevelopment/sitecore-field-fallback#17]
1952 2015:04:12 16:27:23 FATAL Could not add field {10E5A2D4-AB88-450C-81FE-6283506FB423} : meta ogimage for indexable sitecore://master/{CEA9DFAC-34E3-40A8-9C0D-5A20C1F57460}?lang=ja-JP&ver=1
	Exception: System.NullReferenceException
	Message: Object reference not set to an instance of an object.
	Source: System.Web
	   at System.Web.Security.Roles.IsUserInRole(String username, String roleName)
	   at Sitecore.Security.Accounts.RolesInRolesProvider.IsUserInRole(User user, Role targetRole, Boolean includeIndirectMemberships)
	   at Sitecore.Security.AccessControl.AccessRule.RuleApplies(Account account, AccessRight accessRight, PropagationType propagationType, Boolean includeRoleMembers, Boolean includeEveryoneMembers)
	   at Sitecore.Security.AccessControl.AccessRuleCollectionHelper.GetMatchingRule(Account account, AccessRight accessRight, PropagationType propagationType, AccessPermission permission, Boolean includeRoleMembers, Boolean includeEveryoneMembers)
	   at Sitecore.Security.AccessControl.AccessRuleCollectionHelper.GetMatchingRule(Account account, AccessRight accessRight, PropagationType propagationType)
	   at Sitecore.Security.AccessControl.ItemAuthorizationHelper.GetItemAccess(Item item, Account account, AccessRight accessRight, PropagationType propagationType)
	   at Sitecore.Buckets.Security.AuthenticationHelper.GetItemAccess(Item item, Account account, AccessRight accessRight, PropagationType propagationType)
	   at Sitecore.Security.AccessControl.ItemAuthorizationHelper.GetAncestorAccess(Item item, Account account, AccessRight accessRight, PropagationType propagationType)
	   at Sitecore.Security.AccessControl.ItemAuthorizationHelper.GetItemAccess(Item item, Account account, AccessRight accessRight, PropagationType propagationType)
	   at Sitecore.Buckets.Security.AuthenticationHelper.GetItemAccess(Item item, Account account, AccessRight accessRight, PropagationType propagationType)
	   at Sitecore.Security.AccessControl.ItemAuthorizationHelper.GetAncestorAccess(Item item, Account account, AccessRight accessRight, PropagationType propagationType)
	   at Sitecore.Security.AccessControl.ItemAuthorizationHelper.GetItemAccess(Item item, Account account, AccessRight accessRight, PropagationType propagationType)
	   at Sitecore.Buckets.Security.AuthenticationHelper.GetItemAccess(Item item, Account account, AccessRight accessRight, PropagationType propagationType)
	   at Sitecore.Security.AccessControl.ItemAuthorizationHelper.GetAncestorAccess(Item item, Account account, AccessRight accessRight, PropagationType propagationType)
	   at Sitecore.Security.AccessControl.ItemAuthorizationHelper.GetItemAccess(Item item, Account account, AccessRight accessRight, PropagationType propagationType)
	   at Sitecore.Buckets.Security.AuthenticationHelper.GetItemAccess(Item item, Account account, AccessRight accessRight, PropagationType propagationType)
	   at Sitecore.Security.AccessControl.ItemAuthorizationHelper.GetAccess(Item item, Account account, AccessRight accessRight)
	   at Sitecore.Security.AccessControl.AuthorizationProvider.GetAccess(ISecurable entity, Account account, AccessRight accessRight)
	   at Sitecore.Security.AccessControl.AuthorizationManager.IsAllowed(ISecurable entity, AccessRight right, Account account)
	   at Sitecore.Data.Managers.ItemProvider.GetParent(Item item, SecurityCheck securityCheck)
	   at Sitecore.Data.Managers.PipelineBasedItemProvider.ExecuteAndReturnResult[TArgs,TResult](String pipelineName, String pipelineDomain, Func`1 pipelineArgsCreator, Func`1 fallbackResult)
	   at Sitecore.Data.Managers.PipelineBasedItemProvider.GetParent(Item item, SecurityCheck securityCheck)
	   at FieldFallback.Processors.Data.Fields.TemplateFallbackFieldItem.op_Implicit(Field field) in d:\Projects\Sitecore\Development\MAIN\FieldFallback\Processors\Data\Fields\TemplateFallbackFieldItem.cs:line 54
	   at FieldFallback.Processors.AncestorFallbackProcessor.IsEnabledForField(Field field) in d:\Projects\Sitecore\Development\MAIN\FieldFallback\Processors\AncestorFallbackProcessor.cs:line 15
	   at (Object , Object[] )
	   at Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args)
	   at FieldFallback.Data.FallbackValuesProvider.GetFallbackValue(Field field) in d:\Projects\Sitecore\Development\MAIN\FieldFallback\Kernel\Data\FallbackValuesProvider.cs:line 158
	   at FieldFallback.Data.FallbackValuesProvider.GetStandardValue(Field field) in d:\Projects\Sitecore\Development\MAIN\FieldFallback\Kernel\Data\FallbackValuesProvider.cs:line 124
	   at Sitecore.Data.Fields.Field.GetValue(Boolean allowStandardValue, Boolean allowDefaultValue)
	   at Sitecore.ContentSearch.SitecoreItemDataField.get_Value()
	   at Sitecore.ContentSearch.FieldReaders.FieldReaderMap.GetFieldValue(IIndexableDataField field)
	   at Sitecore.ContentSearch.LuceneProvider.LuceneDocumentBuilder.AddField(IIndexableDataField field)
	   at Sitecore.ContentSearch.AbstractDocumentBuilder`1.CheckAndAddField(IIndexable indexable, IIndexableDataField field)

**Comment by seankearney** [comment]
@IvanLieckens According to the stack trace this line is our touch point https://github.com/HedgehogDevelopment/sitecore-field-fallback/blob/master/src/Processors/Data/Fields/TemplateFallbackFieldItem.cs#L54 We aren't doing anythign here other than trying to get the path of the item [we know we have](https://github.com/HedgehogDevelopment/sitecore-field-fallback/blob/master/src/Processors/Data/Fields/TemplateFallbackFieldItem.cs#L47).

Were you able to get anywhere with this?

**Comment by IvanLieckens** [comment]
@seankearney This was a long time ago. I believe to resolve it we wrapped some code with a securitydisabler due to the fact there was no web context and no user for the SC security system.
